name: Check for migration conflicts

on: pull_request

jobs:
  migrator-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Run migrator-conflicts
        uses: PrashantRaj18198/migrator-conflicts@master
        with:
          github_token: ${{ github.token }}
          migration_directories: |
            example/users/migrations
          mention_author: true
