name: Check for migration conflicts

on:
  pull_request:
    types:
      - "opened"
      - "edited"
      - "synchronize"

jobs:
  migrator-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Run migrator-conflicts
        uses: PrashantRaj1898/migrator-conflicts@master
        with:
          migration_directories: |
            example/users/migrations
          mention_author: true
